# GUI code

from tracemalloc import start
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LE_long = QtWidgets.QLabel(self.centralwidget)
        self.LE_long.setGeometry(QtCore.QRect(20, 40, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.LE_long.setFont(font)
        self.LE_long.setObjectName("LE_long")
        self.LE_lat = QtWidgets.QLabel(self.centralwidget)
        self.LE_lat.setGeometry(QtCore.QRect(20, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.LE_lat.setFont(font)
        self.LE_lat.setObjectName("LE_lat")
        self.LE_UTC = QtWidgets.QLabel(self.centralwidget)
        self.LE_UTC.setGeometry(QtCore.QRect(20, 220, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.LE_UTC.setFont(font)
        self.LE_UTC.setObjectName("LE_UTC")
        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(480, 280, 121, 41))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.Long_value = QtWidgets.QLabel(self.centralwidget)
        self.Long_value.setGeometry(QtCore.QRect(220, 30, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Long_value.setFont(font)
        self.Long_value.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Long_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Long_value.setLineWidth(2)
        self.Long_value.setMidLineWidth(1)
        self.Long_value.setAlignment(QtCore.Qt.AlignCenter)
        self.Long_value.setObjectName("Long_value")
        self.lat_value = QtWidgets.QLabel(self.centralwidget)
        self.lat_value.setGeometry(QtCore.QRect(220, 120, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lat_value.setFont(font)
        self.lat_value.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lat_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lat_value.setLineWidth(2)
        self.lat_value.setMidLineWidth(1)
        self.lat_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lat_value.setObjectName("lat_value")
        self.UTC_value = QtWidgets.QLabel(self.centralwidget)
        self.UTC_value.setGeometry(QtCore.QRect(220, 210, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.UTC_value.setFont(font)
        self.UTC_value.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.UTC_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UTC_value.setLineWidth(2)
        self.UTC_value.setMidLineWidth(1)
        self.UTC_value.setAlignment(QtCore.Qt.AlignCenter)
        self.UTC_value.setObjectName("UTC_value")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LE_long.setText(_translate("MainWindow", "Longitude  ="))
        self.LE_lat.setText(_translate("MainWindow", "Latitude     ="))
        self.LE_UTC.setText(_translate("MainWindow", "UTC          ="))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.Long_value.setText(_translate("MainWindow", "0"))
        self.lat_value.setText(_translate("MainWindow", "0"))
        self.UTC_value.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
